name: Backend ci workflow

on:
  pull_request:
    branches:
      - main
      
  workflow_dispatch:
env:
  PYTHON_VERSION: '3.10'

jobs:
  lint-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Use Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install pipenv
      run: |
        cd backend
        pip install pipenv

    - name: Install dependencies
      run: |
        cd backend
        pipenv install --dev

    - name: Run Lint
      run: |
        cd backend
        pipenv run flake8 .
  
  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Use Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install pipenv
      run: |
        cd backend
        pip install pipenv

    - name: Install dependencies
      run: |
        cd backend
        pipenv install --dev

    - name: Run Test
      run: |
        cd backend
        pipenv run pytest

  build-job:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install pipenv
      run: |
        cd backend
        pip install pipenv

    - name: Install dependencies
      run: |
        cd backend
        pipenv install --dev

    - name: Build and run
      run: |
        cd backend
        docker build --tag movie-picture-be:latest .
        docker run -p 5000:5000 --name movie-picture-be -d movie-picture-be